# @package dataset
# List of paths to the dataset directories
path:
#  - path/to/dataset

# Matching files
file_extension: h5

subset_name: None

# Subset partitions
partitions: CVPartition.json

#  Content filtering
channels:
  - cs9-10
  - cs7-8
  - cs5-6
  - cs3-4
  - cs1-2

# Marks in the dataset. Must be a dict. Values can be used to group several marks into single group.
# Check for correct spelling, otherwise creates sequence of zeros.
mark_groups:
  ATRIAL_EGM_CS:AF: SB
  ATRIAL_EGM_CS:SB: SB
  ATRIAL_EGM_CS:AB: SB
  ATRIAL_EGM_CS:ST: SB

